chore: fix web nft linker example doesn't work
axelarnetwork/axelar-examples pull request #113
Opened 2023-04-05 10:09 UTC by npty

# Description

The NFT Linker web example doesn't work because the deployment step that it used isn't compatible with `axelar-gmp-sdk-solidity` version 3.3.0

2023-04-05 10:35 UTC, npty commented on examples-web/scripts/nft-linker/deploy.ts
These changes fix the NFT Linker issue

2023-04-06 17:20 UTC, StephenFluin requested changes
Not working for me. Followed readme from scratch as usual:
```
$ npm run deploy

> axelar-example-web@0.1.0 deploy
> run-s contracts:build contracts:deploy


> axelar-example-web@0.1.0 contracts:build
> hardhat compile

Generating typings for: 3 artifacts in dir: src/types for target: ethers-v5
Successfully generated 56 typings!
Compiled 3 Solidity files successfully

> axelar-example-web@0.1.0 contracts:deploy
> ts-node scripts/deploy-contracts.ts

/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/types/factories/contracts/call-contract/index.ts:4:42 - error TS2307: Cannot find module './MessageReceiver__factory' or its corresponding type declarations.

4 export { MessageReceiver__factory } from "./MessageReceiver__factory";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/types/factories/contracts/call-contract/index.ts:5:40 - error TS2307: Cannot find module './MessageSender__factory' or its corresponding type declarations.

5 export { MessageSender__factory } from "./MessageSender__factory";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1411:41)
    at Module.m._compile (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 2307, 2307 ]
}
ERROR: "contracts:deploy" exited with 1.
```

2023-04-07 08:15 UTC, npty commented
> MessageReceiver__factory

Could you pull the branch and retry `npm run deploy` command to see if that works for you?

2023-04-07 13:59 UTC, StephenFluin approved these changes
LGTM!

2023-04-10 02:45 UTC, merged