imp 3
axelarnetwork/axelar-examples pull request #83
Opened 2023-02-06 12:21 UTC by npty

- fix: remove yarn.lock to prefer package-lock.json based on our npm-based instructions (#61)
- chore: update readme for node.js version
- chore: support node 18
- chore: remove chain config files
- chore: cleanup
- chore: rename `gasReceiver` to `gasService`
- chore: update axelar-local-dev version to `1.2.6`
- feat: add tool to generate a random private key (#60)
- chore: cleanup createPrivateKey script

2023-02-20 14:36 UTC, StephenFluin requested changes

2023-02-20 14:36 UTC, StephenFluin commented on README.md
> +npm run create-private-key
this is the wrong one

2023-02-22 09:49 UTC, npty commented on README.md
> +npm run create-private-key
fixed

2023-02-22 10:33 UTC, StephenFluin approved these changes

2023-02-22 10:33 UTC, merged