[IMP-4] Add GMP Express Examples
axelarnetwork/axelar-examples pull request #87
Opened 2023-02-08 13:46 UTC by npty

# Description

Add GMP Express example. This example extends the [call-contract-with-token example]()

Currently, it has been testing only on testnet, since we didn't have the GMPExpressService contract in local dev yet.

## Tasks

- [ ] Closes #73 
- [ ] Make it works in local

2023-02-08 14:21 UTC, npty commented on examples/evm/call-contract-with-token-express/index.js
> +        [chain.gateway, '0xfb72239394647e97894585D0D93Ca91f6C3852a4'],
updated the hardcoded gas service address here once it's available in https://github.com/axelarnetwork/axelar-cgp-solidity/blob/main/info/testnet.json

2023-02-10 17:51 UTC, re1ro requested changes

2023-02-10 17:51 UTC, re1ro commented on examples/evm/call-contract-with-token-express/DistributionProxy.sol
> +contract DistributionProxy is ExpressProxy {
Delete this file

2023-02-10 17:51 UTC, re1ro commented on examples/evm/call-contract-with-token-express/index.js
> +        DistributionProxy,
use `ExpressProxy` instead of `DistributionProxy`
Alternative option would be calling
```
GMPExpressService.deployExpressProxy()
```

2023-02-22 17:41 UTC, StephenFluin reviewed
Maybe I'm doing something wrong, but `npm run build` is failing for me. 

> $ npm run build
> axelar-examples@1.0.0 build
> rm -rf artifacts && npx hardhat compile
> 
> Error HH404: File @axelar-network/axelar-cgp-solidity/contracts/interfaces/IAxelarExecutable.sol, imported from examples/aptos/call-contract/contracts/HelloWorld.sol, not found.

I also don't know how to get a local wallet with aUSDC, is this something you can do for me as part of the deployment stage? What do I need to do here?

2023-02-22 18:02 UTC, re1ro commented
@npty to fix the Aptos example  `IAxelarExecutable` should be imported from GMP-SDK package 😄

2023-02-23 02:53 UTC, npty commented
> Maybe I'm doing something wrong, but `npm run build` is failing for me.
> 
> > $ npm run build
> > axelar-examples@1.0.0 build
> > rm -rf artifacts && npx hardhat compile
> > Error HH404: File @axelar-network/axelar-cgp-solidity/contracts/interfaces/IAxelarExecutable.sol, imported from examples/aptos/call-contract/contracts/HelloWorld.sol, not found.
> 
> I also don't know how to get a local wallet with aUSDC, is this something you can do for me as part of the deployment stage? What do I need to do here?

`aUSDC` will be funded to your wallet when running `npm run start` https://github.com/axelarnetwork/axelar-examples/blob/d3e693bcfdd09fd1b32985dbacd514a3f6a10a78/scripts/libs/start.js#L19

2023-02-23 14:33 UTC, StephenFluin approved these changes

2023-02-24 02:35 UTC, merged